version: '3.8'

services:
  dashboard:
    image: pixautomatico-dashboard:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pixautomatico.rule=Host(`pixautomatico.inoovaweb.com.br`)"
        - "traefik.http.routers.pixautomatico.entrypoints=websecure"
        - "traefik.http.routers.pixautomatico.tls.certresolver=myresolver"
        - "traefik.docker.network=inoovawebpro"
    environment:
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_PUBLISHABLE_KEY=${VITE_SUPABASE_PUBLISHABLE_KEY}
    networks:
      - inoovawebpro

networks:
  inoovawebpro:
    external: true
